baseURL = "https://yabamiah.github.io/"
languageCode = "en-us"
title = "Yabamiah | Blog"

enableRobotsTXT = true
enableEmoji = true
paginate = 10
summaryLength = 30

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
